"""Add notes to session

Revision ID: b80fa6f4465b
Revises: 7fe2e6081e17
Create Date: 2026-05-14 11:29:52.151556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b80fa6f4465b'
down_revision: Union[str, Sequence[str], None] = '7fe2e6081e17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'notes')
    # ### end Alembic commands ###
